name: "Publish pnpm docker image"
on:
  workflow_dispatch: {}
  push:
    branches:
      - "main"
    paths:
      - "pnpm"

jobs:
  publish:
    name: "Build/Publish Docker image"
    strategy:
      matrix:
        image-name: [pnpm]
        image-tag: [alpine, latest, node:18-alpine]
        image-dir: [pnpm]
        include:
          - registry-username: fernandoarteaga
            registry-password: ${{ secrets.FERNANDO_DOCKERHUB_TOKEN }}
            repository: fernandoarteaga
          - registry: ghcr.io
            registry-username: ${{ github.actor }}
            registry-password: ${{ secrets.GITHUB_TOKEN }}
            repository: docker-images
    uses: ./.github/workflows/push-docker-image.yaml
    with:
      registry: ${{ matrix.registry }}
      registry-username: ${{ matrix.registry-username }}
      registry-password: ${{ matrix.registry-password }}
      repository: ${{ matrix.repository }}
      image-name: ${{ matrix.image-name }}
      image-tag: ${{ matrix.image-tag }}
      image-dir: ${{ matrix.image-dir }}
