name: "Publish pnpm docker image"
on:
  workflow_dispatch: {}
  push:
    branches:
      - "main"
    tags:
      - "pnpm/v*"
    paths:
      - "pnpm/**"

jobs:
  publish:
    name: "Publish Docker image"
    secrets: inherit
    permissions:
      packages: write
      contents: read
    uses: ./.github/workflows/push-docker-image.yaml
    with:
      dockerfile-dir: pnpm
      image-name: pnpm
