name: "Publish docker image"
on:
  workflow_call:
    inputs:
      image-name:
        description: "The name of the docker image"
        required: true
        type: string
      dockerfile-dir:
        description: "The name of the directory where the Dockerfile is located"
        required: true
        type: string


jobs:
  publish:
    name: "Build/Publish Docker image"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Login to Docker Hub"
        uses: docker/login-action@v3
        with:
          username: fernandoarteaga
          password: ${{ secrets.FERNANDO_DOCKERHUB_TOKEN }}
      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            fernandoarteaga/${{ inputs.image-name }}
            ghcr.io/${{ github.repository }}/${{ inputs.image-name }}
          flavor: |
            latest=auto
            prefix=v
          tags: |
            type=semver,pattern={{version}}
            type=sha
            type=ref,event=tag
      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.dockerfile-dir }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
